# Set to true to add reviewers to pull requests
addReviewers: false

# Set to true to add assignees to pull requests
addAssignees: author

runOnDraft: true

  # A list of assignees, overrides reviewers if set
  assignees:
    - pagopa/pagopa-tech
    - jacopocarlini
    - aomegax
    - pasqualespica
