@startuml Table

title Debtor Positions Table

entity DEBT_POSITIONS_TABLE {
  * String partitionKey <<csv_file_name>>
  * String rowKey <<id>>
  --
    String status ("INSERTED" | "CREATED" | "ERROR")
    String paIdIstat
    String paIdCatasto
    String paIdFiscalCode
    String paIdCbill
    String paPecEmail
    String paReferentEmail
    String paReferentName
    String debtorIdFiscalCode
    String paymentNoticeNumber
    String note
    String debtorName
    String debtorEmail
    String amount
    String iuv
    String iupd
    String fiscalCode
    String companyName
    String iban
    String etag ("*")
    String timeStamp (format YYYY-MM-DD hh:mm:ss)
}


@enduml
