@startuml Table

title IUVs Table

entity IUVS_TABLE {
    * String partitionKey <<paIdFiscalCode>>
    * String rowKey <<iuv>>
    --
      String etag ("*")
      String timeStamp (format YYYY-MM-DD hh:mm:ss)
}

@enduml
