# This is a basic workflow to help you get started with Actions

name: 'Auto Assign'

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
 
